server:
  port: 8078
spring:
  application:
    name: boob-posting
  profiles:
    include: jwt
  cloud:
    nacos:
      discovery:
        server-addr: 123.249.39.131
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://123.249.39.131:5432/boob_posting
    username: postgres
    password: 123456
