server:
  port: 8073

spring:
  application:
    name: boob-message
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: boob_message
      username: root
      password: '123456'
      authentication-database: admin
