server:
  port: 8010

spring:
  profiles:
    include: jwt
  application:
    name: boob-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: boob-user
          uri: lb://boob-user
          predicates:
            - Path=/gateway-user/**
          filters:
            - StripPrefix=1
            - PrefixPath=/user

# 解决gateway和web的问题
  main:
    web-application-type: reactive

  logging:
  level:
    org.springframework.cloud.gateway: trace