server:
  port: 8010

spring:
  profiles:
    include: jwt
  application:
    name: boob-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.61.254:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]': # 拦截所有请求
            allowedOriginPatterns:
              - "*"
            allowedHeaders: # 允许在请求中携带的头信息
              - "*"
            allowCredentials: true # 是否允许携带cookie
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            maxAge: 360000 # 这次跨域检测的有效期
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: boob-user
          uri: lb://boob-user
          predicates:
            - Path=/gateway-user/**
          filters:
            - StripPrefix=1
            - PrefixPath=/user
        - id: boob-posting
          uri: lb://boob-posting
          predicates:
            - Path=/gateway-product/**
          filters:
            - StripPrefix=1
            - PrefixPath=/product
        - id: boob-message
          uri: lb:ws://boob-message
          predicates:
            - Path=/websocket/**

# 解决gateway和web的问题
  main:
    web-application-type: reactive

  logging:
  level:
    org.springframework.cloud.gateway: trace