spring:
  profiles:
    include: jwt
  application:
    name: boob-user
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.61.254:8848
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://124.70.61.254:5432/boob_user
    username: postgres
    password: 123456
mybatis.configuration.mapUnderscoreToCamelCase: true
server:
  port: 8077
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
